version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/password"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - neo4j_import:/import
      - neo4j_conf:/conf

volumes:
  neo4j_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_SERVER_IP>,rw
      device: ":/nfs/neo4j/data"
  neo4j_logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_SERVER_IP>,rw
      device: ":/nfs/neo4j/logs"
  neo4j_plugins:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_SERVER_IP>,rw
      device: ":/nfs/neo4j/plugins"
  neo4j_import:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_SERVER_IP>,rw
      device: ":/nfs/neo4j/import"
  neo4j_conf:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_SERVER_IP>,rw
      device: ":/nfs/neo4j/conf"
