version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=mysecretpass
    volumes:
      - ./redis_data:/data
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "mysecretpass", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --requirepass $${REDIS_PASSWORD}

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=mysecretpass
    networks:
      - redis-network
    depends_on:
      redis:
        condition: service_healthy

networks:
  redis-network:
    driver: bridge

volumes:
  redis_data: